{-# OPTIONS_GHC -Wno-orphans #-}

module ClashSynth_PlusSigned where

import Clash.Prelude
import qualified Example.Project

-- | Wrapper for synthesizing Example.Project.plusSigned
-- This module was auto-generated by clash-vscode-yosys extension
-- Original type: Signed 8 -> Signed 8 -> Signed 8

topEntity = Example.Project.plusSigned

{-# ANN topEntity
  (Synthesize
    { t_name = "plus_signed"
    , t_inputs = [ PortName "INA"
                 , PortName "INB"
                 ]
    , t_output = PortName "OUT"
    }) #-}

-- Make sure GHC does not apply optimizations
{-# OPAQUE topEntity #-}
