{-# OPTIONS_GHC -Wno-orphans #-}

module ClashSynth_TestSynth where

import Clash.Prelude
import qualified Test

-- | Wrapper for synthesizing Test.testSynth
-- This module was auto-generated by clash-toolkit extension
-- Original type: Int -> Int

topEntity = Test.testSynth

{-# ANN topEntity
  (Synthesize
    { t_name = "test_synth"
    , t_inputs = [ PortName "INA"
                 ]
    , t_output = PortName "OUT"
    }) #-}

-- Make sure GHC does not apply optimizations
{-# OPAQUE topEntity #-}
