{-# OPTIONS_GHC -Wno-orphans #-}

module ClashSynth_MyFunc where

import Clash.Prelude
import qualified Foo.Bar

-- | Wrapper for synthesizing Foo.Bar.myFunc
-- This module was auto-generated by clash-vscode-yosys extension
-- Original type: Int -> Bool

topEntity = Foo.Bar.myFunc

{-# ANN topEntity
  (Synthesize
    { t_name = "my_func"
    , t_inputs = [ PortName "INA"
                 ]
    , t_output = PortName "OUT"
    }) #-}

-- Make sure GHC does not apply optimizations
{-# OPAQUE topEntity #-}
