{-# OPTIONS_GHC -Wno-orphans #-}

module Test_TopEntity where

import Clash.Prelude
import qualified Example.Project

-- | Wrapper for synthesizing Example.Project.topEntity
-- This module was auto-generated by clash-vscode-yosys extension
-- Original type: Clock Dom50 -> Reset Dom50 -> Enable Dom50 -> Signal Dom50 (Unsigned 8) -> Signal Dom50 (Unsigned 8)

topEntity = Example.Project.topEntity

{-# ANN topEntity
  (Synthesize
    { t_name = "top_entity"
    , t_inputs = [ PortName "CLK"
                 , PortName "RST"
                 , PortName "EN"
                 , PortName "IND"
                 ]
    , t_output = PortName "OUT"
    }) #-}

-- Make sure GHC does not apply optimizations
{-# OPAQUE topEntity #-}
