{-# OPTIONS_GHC -Wno-orphans #-}

module Test_MyComplexFunction where

import Clash.Prelude
import qualified Test

-- | Wrapper for synthesizing Test.myComplexFunction
-- This module was auto-generated by clash-toolkit extension
-- Original type: Int -> Int

topEntity = Test.myComplexFunction

{-# ANN topEntity
  (Synthesize
    { t_name = "my_complex_function"
    , t_inputs = [ PortName "INA"
                 ]
    , t_output = PortName "OUT"
    }) #-}

-- Make sure GHC does not apply optimizations
{-# OPAQUE topEntity #-}
