{-# OPTIONS_GHC -Wno-orphans #-}

module Test_TestFunc where

import Clash.Prelude
import qualified Test

-- | Wrapper for synthesizing Test.testFunc
-- This module was auto-generated by clash-vscode-yosys extension
-- Original type: Unsigned 16 -> Unsigned 16 -> Unsigned 32

topEntity = Test.testFunc

{-# ANN topEntity
  (Synthesize
    { t_name = "test_func"
    , t_inputs = [ PortName "INA"
                 , PortName "INB"
                 ]
    , t_output = PortName "OUT"
    }) #-}

-- Make sure GHC does not apply optimizations
{-# OPAQUE topEntity #-}
