{-# OPTIONS_GHC -Wno-orphans #-}

module Test_AddSigned where

import Clash.Prelude
import qualified Test

-- | Wrapper for synthesizing Test.addSigned
-- This module was auto-generated by clash-toolkit extension
-- Original type: Signed 8 -> Signed 8 -> Signed 8

topEntity = Test.addSigned

{-# ANN topEntity
  (Synthesize
    { t_name = "add_signed"
    , t_inputs = [ PortName "INA"
                 , PortName "INB"
                 ]
    , t_output = PortName "OUT"
    }) #-}

-- Make sure GHC does not apply optimizations
{-# OPAQUE topEntity #-}
