import * as vscode from 'vscode';
import * as path from 'path';
import { promises as fs } from 'fs';
import { process_files } from 'yosys2digitaljs/node';
import { yosys2digitaljs } from 'yosys2digitaljs/core';

/**
 * Manages DigitalJS circuit viewer webview panels
 */
export class DiagramViewer {
	private static currentPanel: vscode.WebviewPanel | undefined;

	/**
	 * Show interactive circuit diagram in a webview panel
	 * 
	 * @param verilogDirOrFiles Either a directory path to scan, or an array of specific Verilog file paths
	 * @param topModule Top module name
	 * @param outputChannel Output channel for logging
	 */
	public static async showDiagram(
		verilogDirOrFiles: string | string[],
		topModule: string,
		outputChannel: vscode.OutputChannel
	): Promise<void> {
		// Collect Verilog files
		let verilogFiles: { [key: string]: string } = {};
		
		if (Array.isArray(verilogDirOrFiles)) {
			// Use provided file list (from manifest)
			outputChannel.appendLine(`Loading ${verilogDirOrFiles.length} Verilog files from manifest`);
			
			try {
				for (const filePath of verilogDirOrFiles) {
					const content = await fs.readFile(filePath, 'utf8');
					const fileName = path.basename(filePath);
					verilogFiles[fileName] = content;
					outputChannel.appendLine(`  - ${fileName} (${content.length} bytes)`);
				}
			} catch (err) {
				vscode.window.showErrorMessage(`Failed to read Verilog files: ${err}`);
				outputChannel.appendLine(`ERROR: Failed to read Verilog: ${err}`);
				return;
			}
		} else {
			// Scan directory (legacy/fallback behavior)
			const verilogDir = verilogDirOrFiles;
			outputChannel.appendLine(`Loading Verilog from: ${verilogDir}`);

			try {
				const files = await fs.readdir(verilogDir);
				const vFiles = files.filter(f => f.endsWith('.v') && !f.includes('_shim'));
				
				outputChannel.appendLine(`Found ${vFiles.length} Verilog files`);
				
				// Read all Verilog files
				for (const vFile of vFiles) {
					const fullPath = path.join(verilogDir, vFile);
					const content = await fs.readFile(fullPath, 'utf8');
					verilogFiles[vFile] = content;
					outputChannel.appendLine(`  - ${vFile} (${content.length} bytes)`);
				}
			} catch (err) {
				vscode.window.showErrorMessage(`Failed to read Verilog files: ${err}`);
				outputChannel.appendLine(`ERROR: Failed to read Verilog: ${err}`);
				return;
			}
		}

		// Convert to DigitalJS format using yosys2digitaljs
		let digitaljsCircuit;
		try {
			outputChannel.appendLine('Running Yosys synthesis and conversion to DigitalJS...');
			outputChannel.appendLine(`Top module: ${topModule}`);
			
			const result = await process_files(verilogFiles, {
				optimize: true,
				fsm: 'nomap',  // Don't expand FSMs
			});
			
			if (result.yosys_stdout) {
				outputChannel.appendLine('\nYosys output:');
				outputChannel.appendLine(result.yosys_stdout);
			}
			if (result.yosys_stderr) {
				outputChannel.appendLine('\nYosys errors/warnings:');
				outputChannel.appendLine(result.yosys_stderr);
			}
			
			if (!result.output) {
				throw new Error('No circuit generated by yosys2digitaljs');
			}
			
			digitaljsCircuit = result.output;
			outputChannel.appendLine(`✓ Converted to DigitalJS (${Object.keys((digitaljsCircuit as { devices?: Record<string, unknown> }).devices || {}).length} devices)`);
		} catch (err: unknown) {
			const msg = err instanceof Error ? err.message : String(err);
			vscode.window.showErrorMessage(`Failed to convert to DigitalJS: ${msg}`);
			outputChannel.appendLine(`ERROR: Conversion failed: ${msg}`);
			if (err instanceof Error && err.stack) {
				outputChannel.appendLine(err.stack);
			}
			return;
		}

		const columnToShowIn = vscode.window.activeTextEditor
			? vscode.window.activeTextEditor.viewColumn
			: undefined;

		if (DiagramViewer.currentPanel) {
			// If we already have a panel, show it
			DiagramViewer.currentPanel.reveal(columnToShowIn);
			DiagramViewer.currentPanel.title = `Circuit: ${topModule}`;
		} else {
			// Otherwise, create a new panel
			DiagramViewer.currentPanel = vscode.window.createWebviewPanel(
				'clashCircuitDiagram',
				`Circuit: ${topModule}`,
				columnToShowIn || vscode.ViewColumn.Two,
				{
					enableScripts: true,
					retainContextWhenHidden: true,
					localResourceRoots: []
				}
			);

			DiagramViewer.currentPanel.onDidDispose(
				() => {
					DiagramViewer.currentPanel = undefined;
				},
				null
			);
		}

		// Update the webview content
		DiagramViewer.currentPanel.webview.html = DiagramViewer.getWebviewContent(
			digitaljsCircuit,
			topModule
		);

		outputChannel.appendLine('✓ Circuit viewer opened');
	}

	/**
	 * Show a circuit diagram from a pre-generated Yosys JSON file.
	 * Used by per-module synthesis mode to display individual module diagrams.
	 */
	public static async showDiagramFromJson(
		jsonPath: string,
		moduleName: string,
		outputChannel: vscode.OutputChannel
	): Promise<void> {
		outputChannel.appendLine(`Loading diagram JSON from: ${jsonPath}`);

		let rawJson: string;
		try {
			rawJson = await fs.readFile(jsonPath, 'utf8');
		} catch (err) {
			vscode.window.showErrorMessage(`Failed to read diagram JSON: ${err}`);
			return;
		}

		let yosysOutput;
		try {
			yosysOutput = JSON.parse(rawJson);
		} catch (err) {
			vscode.window.showErrorMessage(`Invalid JSON in diagram file: ${err}`);
			return;
		}

		// The file is Yosys RTLIL JSON (from write_json), not DigitalJS circuit
		// JSON.  Convert it using the yosys2digitaljs core converter.
		let circuit;
		try {
			circuit = yosys2digitaljs(yosysOutput);
			outputChannel.appendLine(
				`✓ Converted to DigitalJS (${Object.keys((circuit as { devices?: Record<string, unknown> }).devices || {}).length} devices)`
			);
		} catch (err: unknown) {
			const msg = err instanceof Error ? err.message : String(err);
			vscode.window.showErrorMessage(`Failed to convert Yosys JSON to DigitalJS: ${msg}`);
			outputChannel.appendLine(`ERROR: Conversion failed: ${msg}`);
			if (err instanceof Error && err.stack) { outputChannel.appendLine(err.stack); }
			return;
		}

		const columnToShowIn = vscode.window.activeTextEditor
			? vscode.window.activeTextEditor.viewColumn
			: undefined;

		if (DiagramViewer.currentPanel) {
			DiagramViewer.currentPanel.reveal(columnToShowIn);
			DiagramViewer.currentPanel.title = `Circuit: ${moduleName}`;
		} else {
			DiagramViewer.currentPanel = vscode.window.createWebviewPanel(
				'clashCircuitDiagram',
				`Circuit: ${moduleName}`,
				columnToShowIn || vscode.ViewColumn.Two,
				{
					enableScripts: true,
					retainContextWhenHidden: true,
					localResourceRoots: []
				}
			);

			DiagramViewer.currentPanel.onDidDispose(
				() => {
					DiagramViewer.currentPanel = undefined;
				},
				null
			);
		}

		DiagramViewer.currentPanel.webview.html = DiagramViewer.getWebviewContent(
			circuit,
			moduleName
		);

		outputChannel.appendLine('✓ Circuit viewer opened');
	}

	/**
	 * Generate HTML content for the webview with DigitalJS
	 */
	private static getWebviewContent(
		circuit: unknown,
		topModule: string
	): string {
		// Serialize the circuit as JSON for embedding
		const circuitJson = JSON.stringify(circuit);

		return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline' https://cdn.jsdelivr.net; img-src 'self' data: blob:; font-src data: https://cdn.jsdelivr.net;">
    <title>Circuit: ${topModule}</title>

    <!--
      DigitalJS dist/main.js is a self-contained webpack bundle that includes
      jQuery, jQuery-UI, @joint/core 4.x, elkjs, and backbone.
      Do NOT load those libraries separately — duplicate globals cause conflicts.
    -->
    <script src="https://cdn.jsdelivr.net/npm/digitaljs@0.14.2/dist/main.js"></script>
    
    <style>
        body {
            font-family: var(--vscode-font-family);
            color: var(--vscode-foreground);
            background-color: var(--vscode-editor-background);
            padding: 0;
            margin: 0;
            overflow: hidden;
        }
        .container {
            display: flex;
            flex-direction: column;
            height: 100vh;
        }
        .header {
            background-color: var(--vscode-editorGroupHeader-tabsBackground);
            border-bottom: 1px solid var(--vscode-editorGroupHeader-tabsBorder);
            padding: 12px 16px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .title {
            font-size: 14px;
            font-weight: 600;
            color: var(--vscode-foreground);
        }
        .controls {
            display: flex;
            gap: 8px;
            align-items: center;
        }
        .btn {
            padding: 6px 12px;
            background-color: var(--vscode-button-background);
            color: var(--vscode-button-foreground);
            border: none;
            border-radius: 2px;
            cursor: pointer;
            font-size: 12px;
            font-family: var(--vscode-font-family);
        }
        .btn:hover {
            background-color: var(--vscode-button-hoverBackground);
        }
        .btn:disabled {
            opacity: 0.5;
            cursor: not-allowed;
        }
        .btn-secondary {
            background-color: var(--vscode-button-secondaryBackground);
            color: var(--vscode-button-secondaryForeground);
        }
        .btn-secondary:hover {
            background-color: var(--vscode-button-secondaryHoverBackground);
        }
        .status {
            font-size: 11px;
            color: var(--vscode-descriptionForeground);
            margin-left: 12px;
        }
        #paper-container {
            flex: 1;
            overflow: hidden;
            background-color: #ffffff;
            position: relative;
        }
        #paper {
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
        }
        /* Prevent JointJS SVG from clipping content during pan/zoom */
        #paper svg {
            overflow: visible !important;
        }
        .info-banner {
            background-color: var(--vscode-textBlockQuote-background);
            border-left: 4px solid var(--vscode-textBlockQuote-border);
            padding: 8px 12px;
            font-size: 12px;
            color: var(--vscode-foreground);
        }
        .error {
            background-color: var(--vscode-inputValidation-errorBackground);
            border-left-color: var(--vscode-inputValidation-errorBorder);
            color: var(--vscode-errorForeground);
            padding: 12px;
            margin: 20px;
        }
        code {
            background-color: var(--vscode-textCodeBlock-background);
            padding: 2px 4px;
            border-radius: 3px;
            font-family: var(--vscode-editor-font-family);
            font-size: 11px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="title">Interactive Circuit Simulator: ${topModule}</div>
            <div class="controls">
                <button class="btn" id="start-btn" onclick="startSimulation()">▶ Start</button>
                <button class="btn btn-secondary" id="stop-btn" onclick="stopSimulation()" disabled>⏸ Pause</button>
                <button class="btn btn-secondary" onclick="resetSimulation()">⟲ Reset</button>
                <span style="margin: 0 4px;">|</span>
                <button class="btn btn-secondary" onclick="zoomIn()">🔍+ Zoom In</button>
                <button class="btn btn-secondary" onclick="zoomOut()">🔍− Zoom Out</button>
                <button class="btn btn-secondary" onclick="zoomFit()">🔍 Fit</button>
                <span class="status" id="status">Ready</span>
            </div>
        </div>
        <div class="info-banner">
            <strong>DigitalJS Circuit Simulator</strong> - Scroll to zoom (toward cursor), Ctrl+drag or middle-drag to pan. 
            Shortcuts: <code>Ctrl +</code> zoom in, <code>Ctrl -</code> zoom out, <code>Ctrl 0</code> fit to view.
        </div>
        <div id="paper-container">
            <div id="paper"></div>
        </div>
    </div>

    <script>
        let circuit = null;
        let paper = null;
        let _realFitToContent = null; // preserved before we override paper.fitToContent
        let initialFitDone = false;   // true once the first auto-fit has run
        let fitTimer = null;          // debounce timer for initial auto-fit
        let isRunning = false;
        let isPanning = false;
        let panStartX = 0, panStartY = 0, panStartTx = 0, panStartTy = 0;

        const ZOOM_FACTOR = 1.1;
        const MIN_SCALE = 0.05;
        const MAX_SCALE = 10;

        const circuitData = ${circuitJson};

        // ── Helpers ─────────────────────────────────────────────────────────

        // Size the SVG to fill its container.
        function sizePaper() {
            if (!paper) return;
            const c = document.getElementById('paper-container');
            paper.setDimensions(c.clientWidth, c.clientHeight);
        }

        // ── Zoom ─────────────────────────────────────────────────────────────
        //
        // JointJS 4.x matrix layout: screen = scale * world + translate
        //   paper.scale()     → { sx, sy }   (scale factors)
        //   paper.translate() → { tx, ty }   (screen-space pixel offsets)
        //
        // Zoom toward screen point (cx, cy):
        //   world point under cursor = (cursor - translate) / scale
        //   new translate = cursor - newScale * worldPoint

        function zoomAtPoint(newScale, cx, cy) {
            if (!paper) return;
            newScale = Math.max(MIN_SCALE, Math.min(MAX_SCALE, newScale));
            const { sx: oldScale } = paper.scale();
            const { tx: oldTx,  ty: oldTy  } = paper.translate();
            // World coordinates under the cursor in the current transform
            const worldX = (cx - oldTx) / oldScale;
            const worldY = (cy - oldTy) / oldScale;
            // New translate keeps that world point under the cursor
            const newTx = cx - newScale * worldX;
            const newTy = cy - newScale * worldY;
            // paper.scale() and paper.translate() write directly to the SVG
            // matrix — no cell re-render needed.  Do NOT call freeze/resetCells/
            // unfreeze here: that triggers render:done which fires DigitalJS's
            // permanent fitToContent listener and would override the zoom.
            paper.scale(newScale);
            paper.translate(newTx, newTy);
        }

        function zoomFit() {
            if (!_realFitToContent) return;
            try {
                _realFitToContent({ padding: 30, allowNewOrigin: 'any' });
            } catch (e) { console.error('zoomFit:', e); }
        }

        function zoomIn() {
            if (!paper) return;
            const { sx } = paper.scale();
            const c = document.getElementById('paper-container');
            zoomAtPoint(sx * ZOOM_FACTOR, c.clientWidth / 2, c.clientHeight / 2);
        }

        function zoomOut() {
            if (!paper) return;
            const { sx } = paper.scale();
            const c = document.getElementById('paper-container');
            zoomAtPoint(sx / ZOOM_FACTOR, c.clientWidth / 2, c.clientHeight / 2);
        }

        // ── Circuit init ─────────────────────────────────────────────────────

        try {
            circuit = new digitaljs.Circuit(circuitData);
            // displayOn() accepts a plain DOM element (jQuery not required here)
            paper = circuit.displayOn(document.getElementById('paper'));

            if (paper) {
                // ── Block DigitalJS's permanent fitToContent ──────────────────
                //
                // DigitalJS._makePaper() installs a permanent listener:
                //   this.listenTo(paper, 'render:done', () => paper.fitToContent(...))
                //
                // This fires not just on initial load but also when ELK layout
                // completes asynchronously (after the user has started interacting),
                // resetting pan/zoom to the top-left.
                //
                // Fix: override paper.fitToContent with a no-op immediately, so the
                // permanent listener becomes harmless.  We keep _realFitToContent
                // for our explicit zoomFit() and for the one-time initial auto-fit.
                _realFitToContent = paper.fitToContent.bind(paper);
                paper.fitToContent = () => {};

                sizePaper();

                // Do ONE initial fit after the ELK layout has settled.
                // Debounce: each render:done resets the timer; 300 ms of quiet means
                // ELK is done and no more cells are moving.
                paper.on('render:done', () => {
                    if (initialFitDone) return;
                    clearTimeout(fitTimer);
                    fitTimer = setTimeout(() => {
                        if (!initialFitDone && _realFitToContent) {
                            _realFitToContent({ padding: 30, allowNewOrigin: 'any' });
                            initialFitDone = true;
                        }
                    }, 300);
                });

                const el = paper.el;

                // ── Mouse-wheel zoom toward cursor ──
                el.addEventListener('wheel', (e) => {
                    e.preventDefault();
                    // User is interacting — cancel any pending auto-fit so it
                    // doesn't override the new zoom position.
                    initialFitDone = true;
                    clearTimeout(fitTimer);
                    const rect = el.getBoundingClientRect();
                    const { sx: s } = paper.scale();
                    zoomAtPoint(
                        s * (e.deltaY < 0 ? ZOOM_FACTOR : 1 / ZOOM_FACTOR),
                        e.clientX - rect.left,
                        e.clientY - rect.top
                    );
                }, { passive: false });

                // ── Middle-button / Ctrl+left-drag to pan ──
                //
                // JointJS translate is screen-space, so pan delta is just the raw
                // pixel delta — do NOT divide by scale.
                el.addEventListener('pointerdown', (e) => {
                    if (e.button === 1 || (e.button === 0 && e.ctrlKey)) {
                        // User is panning — cancel any pending auto-fit.
                        initialFitDone = true;
                        clearTimeout(fitTimer);
                        isPanning = true;
                        panStartX = e.clientX;
                        panStartY = e.clientY;
                        ({ tx: panStartTx, ty: panStartTy } = paper.translate());
                        el.setPointerCapture(e.pointerId);
                        e.preventDefault();
                    }
                });
                el.addEventListener('pointermove', (e) => {
                    if (!isPanning) return;
                    paper.translate(
                        panStartTx + (e.clientX - panStartX),
                        panStartTy + (e.clientY - panStartY)
                    );
                });
                el.addEventListener('pointerup', (e) => {
                    if (isPanning) { isPanning = false; el.releasePointerCapture(e.pointerId); }
                });
            }

            document.getElementById('status').textContent = 'Circuit loaded';
        } catch (error) {
            console.error('Failed to initialize circuit:', error);
            document.getElementById('paper-container').innerHTML =
                '<div class="error"><strong>Error:</strong> Failed to load circuit: ' +
                error.message + '</div>';
            document.getElementById('status').textContent = 'Error loading circuit';
        }

        // ── Simulation controls ───────────────────────────────────────────────

        function startSimulation() {
            if (!circuit) return;
            try {
                circuit.start();
                isRunning = true;
                document.getElementById('start-btn').disabled = true;
                document.getElementById('stop-btn').disabled = false;
                document.getElementById('status').textContent = 'Simulation running';
            } catch (e) { document.getElementById('status').textContent = 'Error: ' + e.message; }
        }

        function stopSimulation() {
            if (!circuit) return;
            try {
                circuit.stop();
                isRunning = false;
                document.getElementById('start-btn').disabled = false;
                document.getElementById('stop-btn').disabled = true;
                document.getElementById('status').textContent = 'Simulation paused';
            } catch (e) { console.error('stop failed:', e); }
        }

        function resetSimulation() {
            if (!circuit) return;
            try {
                const wasRunning = isRunning;
                if (wasRunning) circuit.stop();
                circuit.reset();
                if (wasRunning) circuit.start();
                document.getElementById('status').textContent = 'Circuit reset';
            } catch (e) { document.getElementById('status').textContent = 'Error: ' + e.message; }
        }

        // ── Resize / keyboard ─────────────────────────────────────────────────

        window.addEventListener('resize', () => {
            if (!paper) return;
            sizePaper();
        });

        document.addEventListener('keydown', (e) => {
            if (!(e.ctrlKey || e.metaKey)) return;
            if (e.key === '+' || e.key === '=') { e.preventDefault(); zoomIn(); }
            else if (e.key === '-')              { e.preventDefault(); zoomOut(); }
            else if (e.key === '0')              { e.preventDefault(); zoomFit(); }
        });
    </script>
</body>
</html>`;
	}
}
