import * as vscode from 'vscode';
import * as path from 'path';
import { promises as fs } from 'fs';
import { process_files } from 'yosys2digitaljs/node';

/**
 * Manages DigitalJS circuit viewer webview panels
 */
export class DiagramViewer {
	private static currentPanel: vscode.WebviewPanel | undefined;

	/**
	 * Show interactive circuit diagram in a webview panel
	 * 
	 * @param verilogDirOrFiles Either a directory path to scan, or an array of specific Verilog file paths
	 * @param topModule Top module name
	 * @param outputChannel Output channel for logging
	 */
	public static async showDiagram(
		verilogDirOrFiles: string | string[],
		topModule: string,
		outputChannel: vscode.OutputChannel
	): Promise<void> {
		// Collect Verilog files
		let verilogFiles: { [key: string]: string } = {};
		
		if (Array.isArray(verilogDirOrFiles)) {
			// Use provided file list (from manifest)
			outputChannel.appendLine(`Loading ${verilogDirOrFiles.length} Verilog files from manifest`);
			
			try {
				for (const filePath of verilogDirOrFiles) {
					const content = await fs.readFile(filePath, 'utf8');
					const fileName = path.basename(filePath);
					verilogFiles[fileName] = content;
					outputChannel.appendLine(`  - ${fileName} (${content.length} bytes)`);
				}
			} catch (err) {
				vscode.window.showErrorMessage(`Failed to read Verilog files: ${err}`);
				outputChannel.appendLine(`ERROR: Failed to read Verilog: ${err}`);
				return;
			}
		} else {
			// Scan directory (legacy/fallback behavior)
			const verilogDir = verilogDirOrFiles;
			outputChannel.appendLine(`Loading Verilog from: ${verilogDir}`);

			try {
				const files = await fs.readdir(verilogDir);
				const vFiles = files.filter(f => f.endsWith('.v') && !f.includes('_shim'));
				
				outputChannel.appendLine(`Found ${vFiles.length} Verilog files`);
				
				// Read all Verilog files
				for (const vFile of vFiles) {
					const fullPath = path.join(verilogDir, vFile);
					const content = await fs.readFile(fullPath, 'utf8');
					verilogFiles[vFile] = content;
					outputChannel.appendLine(`  - ${vFile} (${content.length} bytes)`);
				}
			} catch (err) {
				vscode.window.showErrorMessage(`Failed to read Verilog files: ${err}`);
				outputChannel.appendLine(`ERROR: Failed to read Verilog: ${err}`);
				return;
			}
		}

		// Convert to DigitalJS format using yosys2digitaljs
		let digitaljsCircuit;
		try {
			outputChannel.appendLine('Running Yosys synthesis and conversion to DigitalJS...');
			outputChannel.appendLine(`Top module: ${topModule}`);
			
			const result = await process_files(verilogFiles, {
				optimize: true,
				fsm: 'nomap',  // Don't expand FSMs
			});
			
			if (result.yosys_stdout) {
				outputChannel.appendLine('\nYosys output:');
				outputChannel.appendLine(result.yosys_stdout);
			}
			if (result.yosys_stderr) {
				outputChannel.appendLine('\nYosys errors/warnings:');
				outputChannel.appendLine(result.yosys_stderr);
			}
			
			if (!result.output) {
				throw new Error('No circuit generated by yosys2digitaljs');
			}
			
			digitaljsCircuit = result.output;
			outputChannel.appendLine(`✓ Converted to DigitalJS (${Object.keys(digitaljsCircuit.devices || {}).length} devices)`);
		} catch (err: any) {
			vscode.window.showErrorMessage(`Failed to convert to DigitalJS: ${err?.message || err}`);
			outputChannel.appendLine(`ERROR: Conversion failed: ${err?.message || err}`);
			if (err?.stack) {
				outputChannel.appendLine(err.stack);
			}
			return;
		}

		const columnToShowIn = vscode.window.activeTextEditor
			? vscode.window.activeTextEditor.viewColumn
			: undefined;

		if (DiagramViewer.currentPanel) {
			// If we already have a panel, show it
			DiagramViewer.currentPanel.reveal(columnToShowIn);
			DiagramViewer.currentPanel.title = `Circuit: ${topModule}`;
		} else {
			// Otherwise, create a new panel
			DiagramViewer.currentPanel = vscode.window.createWebviewPanel(
				'clashCircuitDiagram',
				`Circuit: ${topModule}`,
				columnToShowIn || vscode.ViewColumn.Two,
				{
					enableScripts: true,
					retainContextWhenHidden: true,
					localResourceRoots: []
				}
			);

			DiagramViewer.currentPanel.onDidDispose(
				() => {
					DiagramViewer.currentPanel = undefined;
				},
				null
			);
		}

		// Update the webview content
		DiagramViewer.currentPanel.webview.html = DiagramViewer.getWebviewContent(
			digitaljsCircuit,
			topModule
		);

		outputChannel.appendLine('✓ Circuit viewer opened');
	}

	/**
	 * Generate HTML content for the webview with DigitalJS
	 */
	private static getWebviewContent(
		circuit: any,
		topModule: string
	): string {
		// Serialize the circuit as JSON for embedding
		const circuitJson = JSON.stringify(circuit);

		return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline' https://cdn.jsdelivr.net; img-src 'self' data:; font-src https://cdn.jsdelivr.net;">
    <title>Circuit: ${topModule}</title>
    
    <!-- Load DigitalJS from CDN -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/backbone@1.4.0/backbone-min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jointjs@3.6.0/dist/joint.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/jointjs@3.6.0/dist/joint.min.css">
    <script src="https://cdn.jsdelivr.net/npm/digitaljs@0.14.2/dist/main.js"></script>
    
    <style>
        body {
            font-family: var(--vscode-font-family);
            color: var(--vscode-foreground);
            background-color: var(--vscode-editor-background);
            padding: 0;
            margin: 0;
            overflow: hidden;
        }
        .container {
            display: flex;
            flex-direction: column;
            height: 100vh;
        }
        .header {
            background-color: var(--vscode-editorGroupHeader-tabsBackground);
            border-bottom: 1px solid var(--vscode-editorGroupHeader-tabsBorder);
            padding: 12px 16px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .title {
            font-size: 14px;
            font-weight: 600;
            color: var(--vscode-foreground);
        }
        .controls {
            display: flex;
            gap: 8px;
            align-items: center;
        }
        .btn {
            padding: 6px 12px;
            background-color: var(--vscode-button-background);
            color: var(--vscode-button-foreground);
            border: none;
            border-radius: 2px;
            cursor: pointer;
            font-size: 12px;
            font-family: var(--vscode-font-family);
        }
        .btn:hover {
            background-color: var(--vscode-button-hoverBackground);
        }
        .btn:disabled {
            opacity: 0.5;
            cursor: not-allowed;
        }
        .btn-secondary {
            background-color: var(--vscode-button-secondaryBackground);
            color: var(--vscode-button-secondaryForeground);
        }
        .btn-secondary:hover {
            background-color: var(--vscode-button-secondaryHoverBackground);
        }
        .status {
            font-size: 11px;
            color: var(--vscode-descriptionForeground);
            margin-left: 12px;
        }
        #paper-container {
            flex: 1;
            overflow: auto;
            background-color: #ffffff;
            position: relative;
        }
        #paper {
            width: 100%;
            height: 100%;
        }
        .info-banner {
            background-color: var(--vscode-textBlockQuote-background);
            border-left: 4px solid var(--vscode-textBlockQuote-border);
            padding: 8px 12px;
            font-size: 12px;
            color: var(--vscode-foreground);
        }
        .error {
            background-color: var(--vscode-inputValidation-errorBackground);
            border-left-color: var(--vscode-inputValidation-errorBorder);
            color: var(--vscode-errorForeground);
            padding: 12px;
            margin: 20px;
        }
        code {
            background-color: var(--vscode-textCodeBlock-background);
            padding: 2px 4px;
            border-radius: 3px;
            font-family: var(--vscode-editor-font-family);
            font-size: 11px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="title">Interactive Circuit Simulator: ${topModule}</div>
            <div class="controls">
                <button class="btn" id="start-btn" onclick="startSimulation()">▶ Start</button>
                <button class="btn btn-secondary" id="stop-btn" onclick="stopSimulation()" disabled>⏸ Pause</button>
                <button class="btn btn-secondary" onclick="resetSimulation()">⟲ Reset</button>
                <span style="margin: 0 4px;">|</span>
                <button class="btn btn-secondary" onclick="zoomIn()">🔍+ Zoom In</button>
                <button class="btn btn-secondary" onclick="zoomOut()">🔍− Zoom Out</button>
                <button class="btn btn-secondary" onclick="zoomFit()">🔍 Fit</button>
                <span class="status" id="status">Ready</span>
            </div>
        </div>
        <div class="info-banner">
            <strong>DigitalJS Circuit Simulator</strong> - Click gates to inspect, drag to pan, scroll to zoom. 
            Shortcuts: <code>Ctrl/Cmd +</code> zoom in, <code>Ctrl/Cmd -</code> zoom out, <code>Ctrl/Cmd 0</code> fit to view.
            Start simulation to see signal flow in real-time.
        </div>
        <div id="paper-container">
            <div id="paper"></div>
        </div>
    </div>

    <script>
        let circuit = null;
        let paper = null;
        let isRunning = false;
        let zoomLevel = 0;  // Track current zoom level

        // Parse circuit data
        const circuitData = ${circuitJson};

        // Helper function to apply zoom (mirrors DigitalJS scaleAndRefreshPaper)
        function applyZoom(scale) {
            if (!paper) return;
            paper.scale(Math.pow(1.1, scale));
            const graph = paper.model;
            paper.freeze();
            graph.resetCells(graph.getCells());
            paper.unfreeze();
        }

        // Initialize DigitalJS
        try {
            console.log('Initializing DigitalJS with circuit:', circuitData);
            
            // Create the circuit
            circuit = new digitaljs.Circuit(circuitData);
            
            // Display on paper
            paper = circuit.displayOn($('#paper'));
            
            // Enable mouse wheel zooming - DigitalJS uses paper.scale() directly
            if (paper) {
                // Enable mouse wheel zoom
                $(paper.el).on('mousewheel DOMMouseScroll', function(evt) {
                    evt.preventDefault();
                    evt.stopPropagation();
                    const e = evt.originalEvent;
                    
                    const delta = e.wheelDelta ? e.wheelDelta : -e.detail;
                    
                    if (delta > 0) {
                        // Zoom in
                        zoomLevel++;
                        applyZoom(zoomLevel);
                    } else {
                        // Zoom out
                        zoomLevel--;
                        applyZoom(zoomLevel);
                    }
                });
                
                console.log('Mouse wheel zoom enabled');
            }
            
            // Adjust paper size
            setTimeout(() => {
                zoomFit();
            }, 100);
            
            document.getElementById('status').textContent = 'Circuit loaded';
            console.log('Circuit initialized successfully');
        } catch (error) {
            console.error('Failed to initialize circuit:', error);
            document.getElementById('paper-container').innerHTML = 
                '<div class="error"><strong>Error:</strong> Failed to load circuit: ' + 
                error.message + '</div>';
            document.getElementById('status').textContent = 'Error loading circuit';
        }

        function startSimulation() {
            if (!circuit) return;
            
            try {
                circuit.start();
                isRunning = true;
                document.getElementById('start-btn').disabled = true;
                document.getElementById('stop-btn').disabled = false;
                document.getElementById('status').textContent = 'Simulation running';
            } catch (error) {
                console.error('Failed to start simulation:', error);
                document.getElementById('status').textContent = 'Error: ' + error.message;
            }
        }

        function stopSimulation() {
            if (!circuit) return;
            
            try {
                circuit.stop();
                isRunning = false;
                document.getElementById('start-btn').disabled = false;
                document.getElementById('stop-btn').disabled = true;
                document.getElementById('status').textContent = 'Simulation paused';
            } catch (error) {
                console.error('Failed to stop simulation:', error);
            }
        }

        function resetSimulation() {
            if (!circuit) return;
            
            try {
                const wasRunning = isRunning;
                if (wasRunning) {
                    circuit.stop();
                }
                
                // Reset circuit state
                circuit.reset();
                
                if (wasRunning) {
                    circuit.start();
                }
                
                document.getElementById('status').textContent = 'Circuit reset';
            } catch (error) {
                console.error('Failed to reset circuit:', error);
                document.getElementById('status').textContent = 'Error: ' + error.message;
            }
        }

        function zoomFit() {
            if (!paper) return;
            
            try {
                // Reset to default zoom
                zoomLevel = 0;
                applyZoom(zoomLevel);
            } catch (error) {
                console.error('Zoom fit failed:', error);
            }
        }

        function zoomIn() {
            if (!paper) return;
            
            try {
                zoomLevel++;
                applyZoom(zoomLevel);
            } catch (error) {
                console.error('Zoom in failed:', error);
            }
        }

        function zoomOut() {
            if (!paper) return;
            
            try {
                zoomLevel--;
                applyZoom(zoomLevel);
            } catch (error) {
                console.error('Zoom out failed:', error);
            }
        }

        // Auto-resize on window resize
        window.addEventListener('resize', () => {
            if (paper) {
                setTimeout(zoomFit, 100);
            }
        });

        // Keyboard shortcuts for zoom
        document.addEventListener('keydown', (evt) => {
            // Ctrl/Cmd + Plus/Equals = Zoom In
            if ((evt.ctrlKey || evt.metaKey) && (evt.key === '+' || evt.key === '=')) {
                evt.preventDefault();
                zoomIn();
            }
            // Ctrl/Cmd + Minus = Zoom Out
            else if ((evt.ctrlKey || evt.metaKey) && evt.key === '-') {
                evt.preventDefault();
                zoomOut();
            }
            // Ctrl/Cmd + 0 = Zoom to Fit
            else if ((evt.ctrlKey || evt.metaKey) && evt.key === '0') {
                evt.preventDefault();
                zoomFit();
            }
        });
    </script>
</body>
</html>`;
	}
}
